# Generated by Django 3.0.8 on 2020-08-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicos',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
