# Generated by Django 3.0.8 on 2020-08-08 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meta',
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ['created'], 'verbose_name': 'persona', 'verbose_name_plural': 'personas'},
        ),
        migrations.AlterModelTable(
            name='persona',
            table='persona',
        ),
    ]
